apiVersion: v1
kind: Service
metadata:
    name: pushparajnodemultistagedocker
spec:
    type: LoadBalancer
    ports:
    - port: 4002 
    selector:
        app: pushparajnodemultistagedocker